version: '3.5'

networks:
  app_network:
    driver: bridge

services:

  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST: ${HOST}
    ports:
      - 3333:3333

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80